Repository Manchui/Backend, pull requests merged in 2024-10, with the labels that each got.

#6 Feat/user signup 3
  build.gradle
  src/main/java/com/manchui/ManchuiApplication.java
  src/main/java/com/manchui/domain/controller/.gitkeep
  src/main/java/com/manchui/domain/controller/JoinController.java
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/.gitkeep
  src/main/java/com/manchui/domain/dto/JoinDTO.java
  src/main/java/com/manchui/domain/dto/NameDTO.java
  src/main/java/com/manchui/domain/entity/.gitkeep
  src/main/java/com/manchui/domain/entity/User.java
  src/main/java/com/manchui/domain/repository/.gitkeep
  src/main/java/com/manchui/domain/repository/UserRepository.java
  src/main/java/com/manchui/domain/service/.gitkeep
  src/main/java/com/manchui/domain/service/JoinService.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
  src/main/java/com/manchui/global/exception/handler/GlobalExceptionHandler.java
Labels: ✨ Feat

#11 [Feat] 모임 생성 기능 구현
  .env_example
  build.gradle
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/dto/GatheringCreateRequest.java
  src/main/java/com/manchui/domain/dto/GatheringCreateResponse.java
  src/main/java/com/manchui/domain/entity/Gathering.java
  src/main/java/com/manchui/domain/entity/Image.java
  src/main/java/com/manchui/domain/repository/GatheringRepository.java
  src/main/java/com/manchui/domain/repository/ImageRepository.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/domain/service/ImageServiceImpl.java
  src/main/java/com/manchui/domain/service/S3Uploader.java
  src/main/java/com/manchui/global/config/S3Config.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ Feat, 🧹 Chore

#10 [Feat] 로그아웃 기능 구현
  .env_example
  build.gradle
  src/main/java/com/manchui/domain/service/RedisRefreshTokenService.java
  src/main/java/com/manchui/domain/service/ReissueService.java
  src/main/java/com/manchui/global/config/RedisConfig.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
  src/main/java/com/manchui/global/jwt/CustomLogoutFilter.java
  src/main/java/com/manchui/global/jwt/LoginFilter.java
  src/main/resources/application.yml
Labels: ✨ Feat

#25 [Fix] AccessToken 검증 수정
  src/main/java/com/manchui/domain/service/ReissueService.java
  src/main/java/com/manchui/global/jwt/CustomLogoutFilter.java
  src/main/java/com/manchui/global/jwt/JWTFilter.java
  src/main/java/com/manchui/global/jwt/LoginFilter.java
Labels: bug

#15 [Feat] 모임 찾기 기능 구현
  build.gradle
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/dto/GatheringCreateRequest.java
  src/main/java/com/manchui/domain/dto/GatheringListResponse.java
  src/main/java/com/manchui/domain/dto/GatheringPagingResponse.java
  src/main/java/com/manchui/domain/entity/Attendance.java
  src/main/java/com/manchui/domain/entity/Gathering.java
  src/main/java/com/manchui/domain/repository/GatheringRepository.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/domain/service/UserService.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat, 🧹 Chore, 🔨 Refactoring

#16 [Feat] 모임 참여 기능 구현
  build.gradle
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/entity/Attendance.java
  src/main/java/com/manchui/domain/repository/AttendanceRepository.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat

#17 [Feat] 모임 좋아요 기능 구현
  build.gradle
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/entity/Heart.java
  src/main/java/com/manchui/domain/repository/HeartRepository.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat

#20 [Feat] 모임 참여 취소 기능 구현
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/repository/AttendanceRepository.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/global/entity/Timestamped.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat

#29 [Refactor] 모임 목록 조회 및 검색 기능 수정
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/dto/GatheringListResponse.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
Labels: 🔨 Refactoring
