Repository Manchui/Backend, pull requests merged in 2024-11, with the labels that each got.

#33 [Feat] 모임 모집 취소 기능 구현
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/entity/Gathering.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat

#38 [Fix] Security 필터에 CORS설정 추가하여 CORS문제 해결
  Dockerfile
  build.gradle
  src/main/java/com/manchui/global/config/CorsMvcConfig.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
Labels: bug

#42 [Feat] 회원 정보 조회시 가입 날짜 추가
  src/main/java/com/manchui/domain/dto/User/UserEditInfoResponse.java
  src/main/java/com/manchui/domain/dto/User/UserInfoResponse.java
  src/main/java/com/manchui/domain/service/UserService.java
Labels: ✨ Feat

#40 [Feat] 찜한 모임 목록 조회 기능 구현
  docker-compose.yml
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
Labels: ✨ Feat, 🔨 Refactoring

#44 [Feat] 사용자가 작성한 모임 목록 조회 기능 구현
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/User/UserWrittenGatheringsResponse.java
  src/main/java/com/manchui/domain/dto/User/WrittenGathering.java
  src/main/java/com/manchui/domain/repository/GatheringRepository.java
  src/main/java/com/manchui/domain/service/UserService.java
Labels: ✨ Feat

#45 [Feat] 후기 생성 기능 구현
  src/main/java/com/manchui/domain/controller/ReviewController.java
  src/main/java/com/manchui/domain/dto/GatheringCreateRequest.java
  src/main/java/com/manchui/domain/dto/ReviewCreateRequest.java
  src/main/java/com/manchui/domain/dto/ReviewCreateResponse.java
  src/main/java/com/manchui/domain/entity/Heart.java
  src/main/java/com/manchui/domain/entity/Review.java
  src/main/java/com/manchui/domain/repository/ReviewRepository.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringReader.java
  src/main/java/com/manchui/domain/service/GatheringReaderImpl.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/domain/service/ReviewService.java
  src/main/java/com/manchui/domain/service/ReviewServiceImpl.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat, 🔨 Refactoring

#54 [Feat] 후기 수정 기능 구현
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/controller/ReviewController.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringCreateRequest.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringCreateResponse.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringInfoResponse.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringListResponse.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringPagingResponse.java
  src/main/java/com/manchui/domain/dto/review/ReviewCreateRequest.java
  src/main/java/com/manchui/domain/dto/review/ReviewCreateResponse.java
  src/main/java/com/manchui/domain/dto/review/ReviewInfo.java
  src/main/java/com/manchui/domain/dto/review/ReviewPagingResponse.java
  src/main/java/com/manchui/domain/entity/Gathering.java
  src/main/java/com/manchui/domain/entity/Review.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/repository/querydsl/ReviewQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/ReviewQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringReader.java
  src/main/java/com/manchui/domain/service/GatheringReaderImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/domain/service/GatheringStore.java
  src/main/java/com/manchui/domain/service/GatheringStoreImpl.java
  src/main/java/com/manchui/domain/service/ReviewService.java
  src/main/java/com/manchui/domain/service/ReviewServiceImpl.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
Labels: ✨ Feat, 🧹 Chore

#53 [Feat] 사용자가 작성한 리뷰 목록 조회 기능 구현
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/User/UserWrittenReviewsResponse.java
  src/main/java/com/manchui/domain/dto/User/WrittenReviewInfo.java
  src/main/java/com/manchui/domain/repository/ReviewRepository.java
  src/main/java/com/manchui/domain/service/UserService.java
Labels: ✨ Feat

#67 [Feat] 리뷰 작성 가능한 모임 목록 조회 기능 구현
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/User/ReviewableGatheringInfo.java
  src/main/java/com/manchui/domain/dto/User/UserReviewableGatheringsResponse.java
  src/main/java/com/manchui/domain/repository/AttendanceRepository.java
  src/main/java/com/manchui/domain/repository/ReviewRepository.java
  src/main/java/com/manchui/domain/service/UserService.java
Labels: ✨ Feat

#68 [Refactor] 모임 목록 조회 시 회원/비회원 API 통합
  build.gradle
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/dto/CustomUserDetails.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringCreateRequest.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringPagingResponse.java
  src/main/java/com/manchui/domain/dto/review/ReviewDetailPagingResponse.java
  src/main/java/com/manchui/domain/entity/Gathering.java
  src/main/java/com/manchui/domain/repository/GatheringRepository.java
  src/main/java/com/manchui/domain/repository/ReviewRepository.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/domain/service/ImageServiceImpl.java
  src/main/java/com/manchui/global/config/CorsMvcConfig.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/jwt/JWTFilter.java
Labels: 🧹 Chore, 🔨 Refactoring

#70 [Feat] 이메일 중복 검증 기능 구현 및 참여 목록 조회시 조건 추가
  src/main/java/com/manchui/domain/service/JoinService.java
  src/main/java/com/manchui/domain/service/UserService.java
Labels: ✨ Feat

#78 [Refactor] 모임 목록 조회 필터링 추가
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/dto/review/ReviewCreateRequest.java
  src/main/java/com/manchui/domain/entity/Review.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
Labels: 🔨 Refactoring

#75 [Refactor] 토큰 재발급시 AccessToken을 redis에 저장 기능 추가 및 쿠키 옵션 수정
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/User/WrittenReviewInfo.java
  src/main/java/com/manchui/domain/service/ReissueService.java
  src/main/java/com/manchui/domain/service/UserService.java
  src/main/java/com/manchui/global/jwt/JWTFilter.java
Labels: 🔨 Refactoring

#79 [Refactor] 모임 목록 조회 시 페이지네이션 구현 방법 수정
  src/main/java/com/manchui/domain/controller/GatheringController.java
  src/main/java/com/manchui/domain/controller/JoinController.java
  src/main/java/com/manchui/domain/controller/ReissueController.java
  src/main/java/com/manchui/domain/controller/ReviewController.java
  src/main/java/com/manchui/domain/controller/UserController.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringCursorPagingResponse.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringInfoResponse.java
  src/main/java/com/manchui/domain/dto/gathering/GatheringListResponse.java
  src/main/java/com/manchui/domain/repository/GatheringRepository.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringCursorQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringCursorQueryDslImpl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDsl.java
  src/main/java/com/manchui/domain/repository/querydsl/GatheringQueryDslImpl.java
  src/main/java/com/manchui/domain/service/GatheringService.java
  src/main/java/com/manchui/domain/service/GatheringServiceImpl.java
  src/main/java/com/manchui/global/config/SwaggerConfig.java
  src/main/java/com/manchui/global/jwt/JWTFilter.java
Labels: ✨ Feat, 🔨 Refactoring

#85 [Feat] 소셜 로그인 기능 개발 및 application.yml, Dockerfile 수정
  .env_example
  Dockerfile
  build.gradle
  src/main/java/com/manchui/domain/controller/Oauth2Controller.java
  src/main/java/com/manchui/domain/entity/User.java
  src/main/java/com/manchui/domain/service/Oauth2Service.java
  src/main/java/com/manchui/global/config/SecurityConfig.java
  src/main/java/com/manchui/global/exception/ErrorCode.java
  src/main/java/com/manchui/global/jwt/JWTFilter.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: ✨ Feat

#89 [Chore] Github Action CI기능 추가
  .github/workflows/gradle.yml
Labels: 🧹 Chore
